### ISSUE TITLE
[CLI] encryption:fix-encrypted-version shows flle content in the output

### ISSUE THREAD

**Issue by davitol** [owncloud/encryption#143] opened 2019-08-27 15:21 UTC
Tested with oC 10.3 and encryption 1.4.0 RC1. It is NOT a regression

### Steps to reproduce

1. Run command ```occ encryption:fix-encrypted-version  admin```

![Screen Shot 2019-08-27 at 14 52 43](https://user-images.githubusercontent.com/10596560/63784192-90e1ce80-c8ee-11e9-9ef7-a027fb18f0b6.png)

**Comment by sharidas** [comment] 2019-08-28 07:58
This is caused by the usage of method `readFilePart()` of View https://github.com/owncloud/core/blob/master/lib/private/Files/View.php#L474. If we closely look the line https://github.com/owncloud/core/blob/master/lib/private/Files/View.php#L487 echoes to the console, which is why user sees the message pointed out in this issue. 

The usage of this method in the command is made here: https://github.com/owncloud/encryption/blob/master/lib/Command/FixEncryptedVersion.php#L113

Just a reminder, that its not throwing all contents of a file, only a part of the file is read and echoed. The idea here was to check if the file is readable from a certain position till certain position ( like seek ).

**Comment by PVince81** [comment] 2019-09-03 08:25
I missed this and now we released 1.4.0.

If this is always happening, we should fix this with 1.4.1 because the output looks broken.

@sharidas please confirm

**Comment by sharidas** [comment] 2019-09-03 09:07
@PVince81 Yes, you are right. This is always happening. The technical reason is explained https://github.com/owncloud/encryption/issues/143#issuecomment-525629517.

**Comment by karakayasemi** [comment] 2020-12-27 10:57
fixed with #226

**Closed by karakayasemi** 2020-12-27 10:57 UTC
Labels: bug
