### ISSUE TITLE
FixEncryptedVersionTest.php is spamming the drone CI log

### ISSUE THREAD

**Issue by phil-davis** [owncloud/encryption#151] opened 2019-10-10 04:26 UTC
If I delete `FixEncryptedVersionTest.php` then the `phpunit` output is clean.
But with `FixEncryptedVersionTest.php` the output has a few thousand lines of "crud".

Can we redirect that output somewhere else? Or?

**Comment by phil-davis** [comment] 2019-10-10 04:27
@sharidas do you know why various file content... is spewed out when running these unit tests?

**Comment by sharidas** [comment] 2019-10-10 05:47
@phil-davis This is there in my radar and please keep this issue opened. I would like this issue to be pulled into one of the sprint. The root cause is, due to the use of an api `readFilePart` method in the command. To be specific https://github.com/owncloud/core/blob/master/lib/private/Files/View.php#L490 is causing the content to be spitted into console or so.

**Comment by phil-davis** [comment] 2019-10-10 07:47
@sharidas does that line do anything useful?
or is it just 5 minutes to delete it and make a PR?

**Comment by chscherrer** [comment] 2020-01-03 17:57
Has this log-spamming something to do with the fact, that FixEncryptedVersionTest.php consuming high amount of memory when having several TB / over 2 Mio files within the installation?

**Comment by karakayasemi** [comment] 2020-12-27 10:58
fixed with #226

**Closed by karakayasemi** 2020-12-27 10:58 UTC
Labels: technical debt
