### ISSUE TITLE
command to fix encrypted versions shows content of all files

### ISSUE THREAD

**Issue by individual-it** [owncloud/encryption#146] opened 2019-09-10 08:15 UTC
the output of `occ encryption:fix-encrypted-version` contains the content of all files of the user, that is specially difficult and not useful when having long and/or binary files

e.g. 

```
Verifying the content of file /uu1/files/scan0004.pdf
Attempting to fix the path: /uu1/files/scan0004.pdf
Decrement the encrypted version to 1
Increment the encrypted version to 3
Increment the encrypted version to 4
%PDF-1.4

1 0 obj
   << /Type /Catalog
      /Outlines 2 0 R
      /Pages 3 0 R
   >>
endobj

2 0 obj
   << /Type /Outlines
      /Count 0
   >>
endobj

-----------------------------------
snip
-----------------------------------
�n5�(���<�u�k+8�e�.P
                        �g�83�ТS?>v$��|���=�7�T�1D��oڶ�����g���D*e
I�B��`��
������K*�*����f��/Y�ɑ磶�1�?m�̊��
l�i�G=��iT��2o���z!������e�����%�dM#2��1k�@�KE�N4f�f#K�S6�R@�v�N~]�2dk�p��~9b�L~�@�	U9�(��X�m)�:NA�NRJU1|������
                                                                                                                               ��e\������ Q�m��Tm�8�j�O�-Xf�9�o�24�'�"�P�P���ǡ�'�'%ߺ6���k�m �v׾��ʵ���/ �kp�F
NQ�Z��#�J�B�Hl�/R1_?��E��%��/��+N%o3���W�?8�*�]�&��뷔�:��'�<	|����
                                                                 ��
8��e�bE±6A�@�RCh��U2g��_]b>8|B�@Q
�@k������                               �2���\bK�Y�ۗ7�^�K�@��,�:
          J��v�G:c&, e{��Z���3r��O�~C&��"��i��58v�@����Y�{�K���*
����B�F�j�p+���X��x�m�q���E�^@�a��_��                            �
                                          L���$�lG-`�����Y��,*7c���bv]���Gp���(Y� tһf8�b�/����:�8���9!�,E�,v���d�b��O�F�!�mI�
                                                                                                                                           ���l��`�Gz���U�����
�G�O��7Ya-D ��t4�2�-@Լ���5:%�l����h�u�J�4x$���Z/&�l�f���e*'Pu�n
                                                                    {8��v���Xr��c%��/~G�N}�^��th�N+���p�go�"���? gQ�E#��	���#E�{��~$�¹d��!�s�
CT�e�4��!`�ˠ���"5�$���2��~��t���fW?{#]�VєD]>��,�^�D��~Pv�72`?A�@�/��@�۰m�V"�p,vͤ�����]��mA���K$bh�f� ������͡	B��֭b_�ro�JA.$������W��4ж�"F�c���`$; �Ώ`=LZ��A��yj�bYg/4�.Z�?�l_B�*N���/��@a+����[��#{�٦�H�G=$�$CtT!c.păa��DCˢ���A:p&�E<|�L�R�BF3�Q�TT� ����B��`w��PE
4H(m��k(W���4�w�9��`���(�+F��YȜ�)o9�F�t��ˬn�ӱ$D"	�@B !�H�$D"	�@B �'@)µ�d�"\+Y @)µ���"\+� @)µ�ē"\+���I ���:���
                                                                                                                                                   ��B\'iF�i�KJq�`���� ��I�n$@!M�I91/��B�� ���h���� ���K �d))+�sZ (t$����5�>	`X	h;��e�כ�^�!����O
                                                                                                                 6�A	`8"���(j�<�ƣ�m����)v��}}n��̩)x�!^%��I%Y�^�4.]���1�V�������)IEND�B`�The file /uu1/files/folder with space/testimage.png is: OK
Verifying the content of file /uu1/files/folder with space/testimagelarge.svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 600 600" xml:space="preserve" height="2e3" width="3e3" version="1.0" y="0px" x="0px" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" viewBox="0 0 3000 2000"><g transform="matrix(5,0,0,5,0,-500)"><circle cy="300" cx="300" r="300" fill="#c31927"/><path fill="#fff" d="m300 550c-66.8 0-129.6-26-176.8-73.2s-73.2-110-73.2-176.8 26-129.6 73.2-176.8 110-73.2 176.8-73.2 129.6 26 176.8 73.2 73.2 110 73.2 176.8-26 129.6-73.2 176.8-110 73.2-176.8 73.2z"/><path d="m345.7 64.3-45.7 45.7-45.7-45.7c14.9-2.9 30.2-4.3 45.7-4.3s30.8 1.5 45.7 4.3z"/><path d="m345.7 535.7c-14.9 2.9-30.2 4.3-45.7 4.3s-30.8-1.5-45.7-4.3l45.7-45.7 45.7 45.7z"/><path d="m276.8 389.1c0-3.4 1.1-5.9 3.2-7.5s4.8-2.3 7.9-2.3c3.2 0 5.9 0.8 8 2.4s3.1 4.1 3.1 7.5c0 2.3-0.6 4.3-1.8 5.9s-2.9 2.9-5 3.7c-0.1 0-0.3 0-0.5 0.1s-0.4 0.1-0.5 0.1h-6.2c-0.3 0-1-0.2-2-0.7-1.1-0.5-1.8-0.8-2-1-2.8-2-4.2-4.8-4.2-8.2z"/><path d="m320.4 396.8c-2.3-1.3-4.5-2.3-6.6-3.2s-4.2-2.1-6.4-3.7c-0.6-0.2-0.9-0.6-0.9-1.2v-0.3c0.3-0.5 0.9-1.4 1.6-2.7s1.4-2.7 2.2-4.1c0.7-1.4 1.5-2.8 2.2-4.1s1.1-2.2 1.4-2.8c0.2-0.3 0.5-0.7 0.7-1.1s0.6-0.6 1-0.6c0.3 0 0.8 0.3 1.5 0.9 0.6 0.6 1.1 1 1.3 1.1 3 2 6 3.5 9.1 4.7 3 1.2 6.4 1.8 9.9 1.8 3.6 0 6.6-0.6 9.2-1.9s4.7-3 6.2-5.1c1.6-2.1 2.7-4.7 3.4-7.6s1.1-6.1 1.1-9.4c0-2.9-0.3-5.7-0.9-8.5s-1.6-5.3-2.9-7.4c-1.4-2.1-3.2-3.9-5.5-5.2s-5.2-2-8.6-2c-4 0-7.5 1-10.4 3s-5.5 4.5-7.8 7.5h-0.3l-4.8-3.6c-1.5-1.1-2.9-2.3-4.2-3.4s-2.7-2.3-4.2-3.4v-0.9l8.1-52.4h56.2v18.6h-39.3l-4.1 23.5v0.7c3-2.2 5.8-3.6 8.4-4.4 2.6-0.7 5.7-1.1 9.2-1.1 6 0 11 1 15.2 3 4.1 2 7.5 4.7 10.1 8.2s4.5 7.5 5.6 12.2 1.7 9.8 1.7 15.2c0 6.3-0.8 12.1-2.5 17.2-1.7 5.2-4.2 9.6-7.6 13.3s-7.6 6.5-12.6 8.5-10.8 3-17.5 3c-3.1 0-6.1-0.2-9-0.6-3.1-0.3-6.1-0.9-9.2-1.7z"/><path d="m408.9 301 1.2 9.6c1.1-0.9 2.1-2 3-3.1s1.9-2.2 2.9-3.1c2.4-2.3 5-3.7 7.9-4.3s6-0.9 9.2-0.9c4.2 0 8 0.5 11.4 1.4 3.4 1 6.6 3 9.4 6.2 0.5 0.6 1 1.5 1.5 2.7s1.1 2 1.7 2.3c1.9-2.5 3.8-4.6 5.7-6.2 1.9-1.7 3.9-3 6-3.9s4.3-1.6 6.8-2c2.4-0.4 5.2-0.5 8.3-0.5 5.2 0 9.7 0.6 13.3 1.7s7.2 3.8 10.8 7.9c0.7 1 1.3 2.1 1.9 3.6 0.5 1.4 1.2 2.3 1.9 2.7 0.6 2 1.2 4.2 1.9 6.6s1 4.6 1 6.8v70.8h-21.4v-60.8c0-2.5-0.2-5-0.6-7.4s-1.1-4.7-2.1-6.7-2.4-3.7-4.3-4.9c-1.8-1.2-4.2-1.9-7-1.9-3 0-5.8 0.7-8.5 2.2s-4.5 3.7-5.4 6.5c-0.4 0.8-0.8 2-1.2 3.5-0.5 1.5-0.7 2.3-0.7 2.4v67h-22.1v-63.6c0-2.3-0.3-4.5-0.8-6.6s-1.3-4.1-2.4-5.8-2.5-3.1-4.3-4.1-3.9-1.5-6.4-1.5c-3.2 0-6.3 0.9-9.4 2.7s-4.9 4.4-5.6 7.8c-0.1 0.6-0.2 1.3-0.4 2.1-0.1 0.8-0.3 1.7-0.4 2.5-0.2 0.8-0.4 1.9-0.6 3.2v63.3h-21.9v-98.2h19.7z"/><path d="m168.5 397.1c-3-1.6-6.2-2.9-9.5-3.8s-6.4-2.3-9.5-4.2l-12.3-7.3v-2.4c1.9-4.2 3.5-7.7 4.9-10.5s2.9-5.6 4.4-8.5 2.9-5.3 4-7.1c0.2-0.5 0.6-1.2 1.2-2.1s1-1.5 1.2-1.7h0.7c1.2 0 2.6 0.4 4.4 1.2s3.6 1.8 5.6 3 3.8 2.3 5.6 3.5 3.3 2.1 4.7 2.8c4.7 2.1 9.5 3.6 14.4 4.5s9.7 1.4 14.4 1.4c12.6 0 22.4-3.1 29.4-9.2s10.5-15.5 10.5-28c0-9.1-2.3-16.9-7-23.5s-11.9-10.2-21.7-10.6c-1.2 0-3.3-0.1-6.5-0.2s-6.4-0.2-9.8-0.3-6.7-0.2-9.8-0.2h-6.5v-35.2l26.6-1.7c0.5 0 2.2-0.4 5.1-1.2s5.1-1.4 6.5-1.9c6.1-1.9 10.4-5.3 13.1-10.4s4-10.7 4-16.7c0-10.5-3-18-8.9-22.6-6-4.6-13.8-7-23.6-7-8.6 0-16.6 1.7-24 5.1s-14.5 7.5-21.5 12.4h-0.6c-1.2 0-2-0.7-2.6-2.1s-1.1-2.3-1.6-2.8c-2.3-4.2-4.7-8.3-7-12.4s-4.3-8.4-6-13.1l-0.4-0.7c0-0.7 0.3-1.2 0.9-1.4s1.2-0.6 1.9-1c0.2-0.2 1-0.8 2.4-1.6s2.9-1.6 4.4-2.4 2.9-1.6 4.2-2.4 2.2-1.3 2.6-1.6c0.2 0 1-0.3 2.3-0.9s2.8-1.2 4.6-1.9 3.5-1.4 5.3-2.1 3.2-1.3 4.4-1.7c0.2 0 0.6-0.1 1.2-0.3s1-0.3 1.2-0.3c0.2-0.2 0.5-0.4 0.9-0.5s0.6-0.3 0.9-0.5c5.4-1.2 10.7-2 16.1-2.4 5.4-0.5 11-0.7 16.8-0.7 5.1 0 10.1 0.2 14.9 0.5s9.6 1.2 14.5 2.6c3.3 0.9 6.8 2.4 10.5 4.5s7.2 4.5 10.5 7.3 6.2 5.9 8.8 9.2c2.6 3.4 4.4 6.7 5.6 9.9 0.2 1.2 0.6 2.5 1 4 0.5 1.5 0.9 3.1 1.4 4.7s1 3.6 1.8 5.9v27.2c0 2.8-0.6 5.6-1.8 8.4s-2.6 5.5-4.4 8c-1.8 2.6-3.7 4.9-6 7.1-2.2 2.2-4.3 4.1-6.1 5.7-0.2 0.2-0.8 0.6-1.6 1.2s-1.8 1.2-2.8 1.7c-1 0.6-2 1.2-3 1.7l-1.8 1.2-0.7 0.7c0.7 0.5 2.3 1.2 4.9 2.1s4.2 1.6 4.9 2.1c4.9 2.1 8.9 5.1 12.1 9.1s5.7 8.4 7.5 13.2c1.9 4.9 3.2 9.9 3.8 15.2 0.7 5.2 1 10.2 1 14.8 0 12.3-2.5 24.2-7.5 35.5-5 11.4-13.1 20.2-24.3 26.5-1.9 1.2-3.9 2.1-6.1 2.8s-4.3 1.6-6.1 2.8c-1.2 0.5-3.6 1-7.4 1.7-3.7 0.7-6.2 1.3-7.4 1.7-0.5 0-1.5 0.1-3 0.3s-2.4 0.3-2.6 0.3h-30.8c-0.2 0-1.1-0.1-2.6-0.3s-2.5-0.3-3-0.3c-0.7-0.2-1.8-0.5-3.3-0.7s-3.2-0.5-4.9-0.9c-1.8-0.3-3.4-0.7-4.9-1-1.3-0.7-2.4-1-3.1-1.2z"/></g></svg>
The file /uu1/files/folder with space/testimagelarge.svg is: OK
Verifying the content of file /uu1/files/folder with space/simple-empty-folder/.gitkeep
The file /uu1/files/folder with space/simple-empty-folder/.gitkeep is: OK
Verifying the content of file /uu1/files/0/for-git-commit
this file is only here because git does not allow to commit empty foldersThe file /uu1/files/0/for-git-commit is: OK
Verifying the content of file /uu1/files/0/lorem.txt
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.The file /uu1/files/0/lorem.txt is: OK
Verifying the content of file /uu1/files/'single'quotes/for-git-commit
this file is only here because git does not allow to commit empty foldersThe file /uu1/files/'single'quotes/for-git-commit is: OK
Verifying the content of file /uu1/files/'single'quotes/lorem.txt
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.The file /uu1/files/'single'quotes/lorem.txt is: OK
Verifying the content of file /uu1/files/'single'quotes/simple-empty-folder/for-git-commit
this file is only here because git does not allow to commit empty foldersThe file /uu1/files/'single'quotes/simple-empty-folder/for-git-commit is: OK
artur@deepthought2:~/www/owncloud-10.3.0/alpha2$ 62;c62;c62;c
```

**Comment by davitol** [comment] 2019-09-17 08:30
Dupe of https://github.com/owncloud/encryption/issues/143 . Let's close this one.

**Closed by davitol** 2019-09-17 08:30 UTC
Labels: bug
