### ISSUE TITLE
[QA] document if use_legacy_encoding is required when updating from 1.4.0

### ISSUE THREAD

**Issue by jnweiger** [owncloud/encryption#255] opened 2021-03-17 00:14 UTC
seen in oc 10.7.0 RC1 and encrption 1.5.0 RC1
after upgrade from 1.4.0

the system already has files encrypted in old asccy encrption.
occ upgrade noticed the update encryption app
but `occ config:system:get encryption.use_legacy_encoding` reports empty. BAD.

As a user, I am uncertain if old encrypted files would be readable at all without legacy mode.
Personally I assume they are, as new heades have `encoding:binary`, which old ascii encoding does not have.

To be on the safe side, I first started with 
`occ config:system:set encryption.use_legacy_encoding --type boolean --value True`
checked that UI and clients can read write files, and then diabled use_legacy_encoding and checked again...

**Comment by jnweiger** [comment] 2021-03-17 01:24
In an update where use_legacy_encoding was not used:

Desktop client 2.7.7 rc1 runs into issues:

```
   17.03.21 02:01:17,                                                                ,               testpilotcloud3,Unable to find local sync folder.
   17.03.21 02:22:33,                                             ownCloud Manual.pdf,               testpilotcloud5,Server replied "403 Forbidden" to "MOVE https://135.181.46.217/owncloud/remote.php/dav/files/admin/ownCloud Manual.pdf" (skipped due to earlier error, trying again in 10 second(s))
   17.03.21 02:22:33,                             SFTP1/photo_2020-04-29_17-19-39.jpg,               testpilotcloud5,Server replied "500 Internal Server Error" to "GET https://135.181.46.217/owncloud/remote.php/dav/files/admin/SFTP1/photo_2020-04-29_17-19-39.jpg" (Bad Signature) (skipped due to earlier error, trying again in 10 second(s))

**Comment by karakayasemi** [comment] 2021-03-17 20:55
`use_legacy_encoding` config option is only added to write acceptance tests easier. It is not expected to add this config option. In default, old files should be readable, but new files should be written with binary encoding.

Do we have exact steps to reproduce the client issue?

**Comment by micbar** [comment] 2021-03-18 16:26
@jnweiger can you provide steps to reproduce?

Raising Prio @karakayasemi 

10.7.0 is p1, above all other tasks.

**Comment by butonic** [comment] 2021-03-19 09:31
@jnweiger is `SFTP1` an external storage?

**Comment by C0rby** [comment] 2021-03-19 10:28
I couldn't reproduce the client issue. My steps were:

- Setup owncloud from release-10.7.0 branch
- Enable encryption app v1.4.0
- Upload some files
- Verify that they are stored with the base64 encoding
- Update encryption app to the version in release-1.5.0
- Upload some files
- Verify that they are stored with binary encoding
- Setup account in desktop client
- Sync files via desktop client
- Verify that files are synced in local filesystem and "readable"

**Comment by karakayasemi** [comment] 2021-03-19 11:15
I could not reproduce either. It can be related to external storage also. If it is not a regression, IMHO we can say not a blocker.

**Comment by micbar** [comment] 2021-03-19 11:36
@karakayasemi 

Not a blocker as long as new tests show no issues.

@C0rby @IljaN Can you try to reproduce on SFTP

**Comment by IljaN** [comment] 2021-03-19 14:20
We could not reproduce. Files moved from an encrypted primary storage to an unencrypted SFTP sync correctly.

**Comment by micbar** [comment] 2021-03-19 14:28
thanks, closing.

**Closed by micbar** 2021-03-19 14:28 UTC
Labels: needs investigation, p1-urgent
